#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker2026"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "ca3dadbf6be34410be74cd3b584bbc9e" }
]

[assets]
directory = "./public"
